vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    tech_image:
      uri_prefix: /uploads/technologies
      upload_destination: '%kernel.project_dir%/public/uploads/technologies'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
